/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrivatePoolLeavePostRequest
 */
export interface PrivatePoolLeavePostRequest {
    /**
     * 
     * @type {string}
     * @memberof PrivatePoolLeavePostRequest
     */
    poolId: string;
    /**
     * 
     * @type {string}
     * @memberof PrivatePoolLeavePostRequest
     */
    tokenAmount: string;
}

/**
 * Check if a given object implements the PrivatePoolLeavePostRequest interface.
 */
export function instanceOfPrivatePoolLeavePostRequest(value: object): value is PrivatePoolLeavePostRequest {
    if (!('poolId' in value) || value['poolId'] === undefined) return false;
    if (!('tokenAmount' in value) || value['tokenAmount'] === undefined) return false;
    return true;
}

export function PrivatePoolLeavePostRequestFromJSON(json: any): PrivatePoolLeavePostRequest {
    return PrivatePoolLeavePostRequestFromJSONTyped(json, false);
}

export function PrivatePoolLeavePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivatePoolLeavePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'poolId': json['pool_id'],
        'tokenAmount': json['token_amount'],
    };
}

export function PrivatePoolLeavePostRequestToJSON(json: any): PrivatePoolLeavePostRequest {
    return PrivatePoolLeavePostRequestToJSONTyped(json, false);
}

export function PrivatePoolLeavePostRequestToJSONTyped(value?: PrivatePoolLeavePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pool_id': value['poolId'],
        'token_amount': value['tokenAmount'],
    };
}

