/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrivatePoolTasksGet200ResponseInner
 */
export interface PrivatePoolTasksGet200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof PrivatePoolTasksGet200ResponseInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PrivatePoolTasksGet200ResponseInner
     */
    poolId: string;
    /**
     * 
     * @type {string}
     * @memberof PrivatePoolTasksGet200ResponseInner
     */
    type: PrivatePoolTasksGet200ResponseInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PrivatePoolTasksGet200ResponseInner
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof PrivatePoolTasksGet200ResponseInner
     */
    createdAt: number;
    /**
     * 
     * @type {number}
     * @memberof PrivatePoolTasksGet200ResponseInner
     */
    updatedAt: number;
    /**
     * 
     * @type {string}
     * @memberof PrivatePoolTasksGet200ResponseInner
     */
    baseAmount: string;
    /**
     * 
     * @type {string}
     * @memberof PrivatePoolTasksGet200ResponseInner
     */
    quoteAmount: string;
}


/**
 * @export
 */
export const PrivatePoolTasksGet200ResponseInnerTypeEnum = {
    Join: 'join',
    Leave: 'leave'
} as const;
export type PrivatePoolTasksGet200ResponseInnerTypeEnum = typeof PrivatePoolTasksGet200ResponseInnerTypeEnum[keyof typeof PrivatePoolTasksGet200ResponseInnerTypeEnum];


/**
 * Check if a given object implements the PrivatePoolTasksGet200ResponseInner interface.
 */
export function instanceOfPrivatePoolTasksGet200ResponseInner(value: object): value is PrivatePoolTasksGet200ResponseInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('poolId' in value) || value['poolId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('baseAmount' in value) || value['baseAmount'] === undefined) return false;
    if (!('quoteAmount' in value) || value['quoteAmount'] === undefined) return false;
    return true;
}

export function PrivatePoolTasksGet200ResponseInnerFromJSON(json: any): PrivatePoolTasksGet200ResponseInner {
    return PrivatePoolTasksGet200ResponseInnerFromJSONTyped(json, false);
}

export function PrivatePoolTasksGet200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivatePoolTasksGet200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'poolId': json['pool_id'],
        'type': json['type'],
        'status': json['status'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
        'baseAmount': json['base_amount'],
        'quoteAmount': json['quote_amount'],
    };
}

export function PrivatePoolTasksGet200ResponseInnerToJSON(json: any): PrivatePoolTasksGet200ResponseInner {
    return PrivatePoolTasksGet200ResponseInnerToJSONTyped(json, false);
}

export function PrivatePoolTasksGet200ResponseInnerToJSONTyped(value?: PrivatePoolTasksGet200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'pool_id': value['poolId'],
        'type': value['type'],
        'status': value['status'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
        'base_amount': value['baseAmount'],
        'quote_amount': value['quoteAmount'],
    };
}

