/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrivatePoolJoinPostRequest
 */
export interface PrivatePoolJoinPostRequest {
    /**
     * 
     * @type {string}
     * @memberof PrivatePoolJoinPostRequest
     */
    poolId: string;
    /**
     * 
     * @type {string}
     * @memberof PrivatePoolJoinPostRequest
     */
    baseAmount: string;
    /**
     * 
     * @type {string}
     * @memberof PrivatePoolJoinPostRequest
     */
    quoteAmount: string;
}

/**
 * Check if a given object implements the PrivatePoolJoinPostRequest interface.
 */
export function instanceOfPrivatePoolJoinPostRequest(value: object): value is PrivatePoolJoinPostRequest {
    if (!('poolId' in value) || value['poolId'] === undefined) return false;
    if (!('baseAmount' in value) || value['baseAmount'] === undefined) return false;
    if (!('quoteAmount' in value) || value['quoteAmount'] === undefined) return false;
    return true;
}

export function PrivatePoolJoinPostRequestFromJSON(json: any): PrivatePoolJoinPostRequest {
    return PrivatePoolJoinPostRequestFromJSONTyped(json, false);
}

export function PrivatePoolJoinPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivatePoolJoinPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'poolId': json['pool_id'],
        'baseAmount': json['base_amount'],
        'quoteAmount': json['quote_amount'],
    };
}

export function PrivatePoolJoinPostRequestToJSON(json: any): PrivatePoolJoinPostRequest {
    return PrivatePoolJoinPostRequestToJSONTyped(json, false);
}

export function PrivatePoolJoinPostRequestToJSONTyped(value?: PrivatePoolJoinPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pool_id': value['poolId'],
        'base_amount': value['baseAmount'],
        'quote_amount': value['quoteAmount'],
    };
}

