/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrivateOrdersCancelAllPostRequest
 */
export interface PrivateOrdersCancelAllPostRequest {
    /**
     * 
     * @type {string}
     * @memberof PrivateOrdersCancelAllPostRequest
     */
    symbol: string;
}

/**
 * Check if a given object implements the PrivateOrdersCancelAllPostRequest interface.
 */
export function instanceOfPrivateOrdersCancelAllPostRequest(value: object): value is PrivateOrdersCancelAllPostRequest {
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    return true;
}

export function PrivateOrdersCancelAllPostRequestFromJSON(json: any): PrivateOrdersCancelAllPostRequest {
    return PrivateOrdersCancelAllPostRequestFromJSONTyped(json, false);
}

export function PrivateOrdersCancelAllPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivateOrdersCancelAllPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'symbol': json['symbol'],
    };
}

export function PrivateOrdersCancelAllPostRequestToJSON(json: any): PrivateOrdersCancelAllPostRequest {
    return PrivateOrdersCancelAllPostRequestToJSONTyped(json, false);
}

export function PrivateOrdersCancelAllPostRequestToJSONTyped(value?: PrivateOrdersCancelAllPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'symbol': value['symbol'],
    };
}

