/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrivatePoolTasksGet200ResponseInnerSpentInner
 */
export interface PrivatePoolTasksGet200ResponseInnerSpentInner {
    /**
     * 
     * @type {string}
     * @memberof PrivatePoolTasksGet200ResponseInnerSpentInner
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof PrivatePoolTasksGet200ResponseInnerSpentInner
     */
    amount: string;
}

/**
 * Check if a given object implements the PrivatePoolTasksGet200ResponseInnerSpentInner interface.
 */
export function instanceOfPrivatePoolTasksGet200ResponseInnerSpentInner(value: object): value is PrivatePoolTasksGet200ResponseInnerSpentInner {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function PrivatePoolTasksGet200ResponseInnerSpentInnerFromJSON(json: any): PrivatePoolTasksGet200ResponseInnerSpentInner {
    return PrivatePoolTasksGet200ResponseInnerSpentInnerFromJSONTyped(json, false);
}

export function PrivatePoolTasksGet200ResponseInnerSpentInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivatePoolTasksGet200ResponseInnerSpentInner {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'amount': json['amount'],
    };
}

export function PrivatePoolTasksGet200ResponseInnerSpentInnerToJSON(json: any): PrivatePoolTasksGet200ResponseInnerSpentInner {
    return PrivatePoolTasksGet200ResponseInnerSpentInnerToJSONTyped(json, false);
}

export function PrivatePoolTasksGet200ResponseInnerSpentInnerToJSONTyped(value?: PrivatePoolTasksGet200ResponseInnerSpentInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'amount': value['amount'],
    };
}

