/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrivatePoolPositionsGet200ResponseInner
 */
export interface PrivatePoolPositionsGet200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof PrivatePoolPositionsGet200ResponseInner
     */
    symbol: string;
    /**
     * 
     * @type {string}
     * @memberof PrivatePoolPositionsGet200ResponseInner
     */
    posId: string;
    /**
     * 
     * @type {string}
     * @memberof PrivatePoolPositionsGet200ResponseInner
     */
    priceLower: string;
    /**
     * 
     * @type {string}
     * @memberof PrivatePoolPositionsGet200ResponseInner
     */
    priceUpper: string;
    /**
     * 
     * @type {string}
     * @memberof PrivatePoolPositionsGet200ResponseInner
     */
    baseAmount: string;
    /**
     * 
     * @type {string}
     * @memberof PrivatePoolPositionsGet200ResponseInner
     */
    quoteAmount: string;
    /**
     * 
     * @type {string}
     * @memberof PrivatePoolPositionsGet200ResponseInner
     */
    poolFeePrct: string;
    /**
     * 
     * @type {string}
     * @memberof PrivatePoolPositionsGet200ResponseInner
     */
    lifetimeRewardsBase: string;
    /**
     * 
     * @type {string}
     * @memberof PrivatePoolPositionsGet200ResponseInner
     */
    lifetimeRewardsQuote: string;
    /**
     * 
     * @type {string}
     * @memberof PrivatePoolPositionsGet200ResponseInner
     */
    pendingRewardsBase: string;
    /**
     * 
     * @type {string}
     * @memberof PrivatePoolPositionsGet200ResponseInner
     */
    pendingRewardsQuote: string;
    /**
     * 
     * @type {number}
     * @memberof PrivatePoolPositionsGet200ResponseInner
     */
    timestamp: number;
    /**
     * 
     * @type {number}
     * @memberof PrivatePoolPositionsGet200ResponseInner
     */
    createdAt: number;
    /**
     * 
     * @type {boolean}
     * @memberof PrivatePoolPositionsGet200ResponseInner
     */
    active?: boolean;
}

/**
 * Check if a given object implements the PrivatePoolPositionsGet200ResponseInner interface.
 */
export function instanceOfPrivatePoolPositionsGet200ResponseInner(value: object): value is PrivatePoolPositionsGet200ResponseInner {
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('posId' in value) || value['posId'] === undefined) return false;
    if (!('priceLower' in value) || value['priceLower'] === undefined) return false;
    if (!('priceUpper' in value) || value['priceUpper'] === undefined) return false;
    if (!('baseAmount' in value) || value['baseAmount'] === undefined) return false;
    if (!('quoteAmount' in value) || value['quoteAmount'] === undefined) return false;
    if (!('poolFeePrct' in value) || value['poolFeePrct'] === undefined) return false;
    if (!('lifetimeRewardsBase' in value) || value['lifetimeRewardsBase'] === undefined) return false;
    if (!('lifetimeRewardsQuote' in value) || value['lifetimeRewardsQuote'] === undefined) return false;
    if (!('pendingRewardsBase' in value) || value['pendingRewardsBase'] === undefined) return false;
    if (!('pendingRewardsQuote' in value) || value['pendingRewardsQuote'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function PrivatePoolPositionsGet200ResponseInnerFromJSON(json: any): PrivatePoolPositionsGet200ResponseInner {
    return PrivatePoolPositionsGet200ResponseInnerFromJSONTyped(json, false);
}

export function PrivatePoolPositionsGet200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivatePoolPositionsGet200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'symbol': json['symbol'],
        'posId': json['pos_id'],
        'priceLower': json['price_lower'],
        'priceUpper': json['price_upper'],
        'baseAmount': json['base_amount'],
        'quoteAmount': json['quote_amount'],
        'poolFeePrct': json['pool_fee_prct'],
        'lifetimeRewardsBase': json['lifetime_rewards_base'],
        'lifetimeRewardsQuote': json['lifetime_rewards_quote'],
        'pendingRewardsBase': json['pending_rewards_base'],
        'pendingRewardsQuote': json['pending_rewards_quote'],
        'timestamp': json['timestamp'],
        'createdAt': json['created_at'],
        'active': json['active'] == null ? undefined : json['active'],
    };
}

export function PrivatePoolPositionsGet200ResponseInnerToJSON(json: any): PrivatePoolPositionsGet200ResponseInner {
    return PrivatePoolPositionsGet200ResponseInnerToJSONTyped(json, false);
}

export function PrivatePoolPositionsGet200ResponseInnerToJSONTyped(value?: PrivatePoolPositionsGet200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'symbol': value['symbol'],
        'pos_id': value['posId'],
        'price_lower': value['priceLower'],
        'price_upper': value['priceUpper'],
        'base_amount': value['baseAmount'],
        'quote_amount': value['quoteAmount'],
        'pool_fee_prct': value['poolFeePrct'],
        'lifetime_rewards_base': value['lifetimeRewardsBase'],
        'lifetime_rewards_quote': value['lifetimeRewardsQuote'],
        'pending_rewards_base': value['pendingRewardsBase'],
        'pending_rewards_quote': value['pendingRewardsQuote'],
        'timestamp': value['timestamp'],
        'created_at': value['createdAt'],
        'active': value['active'],
    };
}

