/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrivateOrdersGet200ResponseInnerFee
 */
export interface PrivateOrdersGet200ResponseInnerFee {
    /**
     * 
     * @type {string}
     * @memberof PrivateOrdersGet200ResponseInnerFee
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof PrivateOrdersGet200ResponseInnerFee
     */
    cost: string;
    /**
     * 
     * @type {string}
     * @memberof PrivateOrdersGet200ResponseInnerFee
     */
    rate: string;
}

/**
 * Check if a given object implements the PrivateOrdersGet200ResponseInnerFee interface.
 */
export function instanceOfPrivateOrdersGet200ResponseInnerFee(value: object): value is PrivateOrdersGet200ResponseInnerFee {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('cost' in value) || value['cost'] === undefined) return false;
    if (!('rate' in value) || value['rate'] === undefined) return false;
    return true;
}

export function PrivateOrdersGet200ResponseInnerFeeFromJSON(json: any): PrivateOrdersGet200ResponseInnerFee {
    return PrivateOrdersGet200ResponseInnerFeeFromJSONTyped(json, false);
}

export function PrivateOrdersGet200ResponseInnerFeeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivateOrdersGet200ResponseInnerFee {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'cost': json['cost'],
        'rate': json['rate'],
    };
}

export function PrivateOrdersGet200ResponseInnerFeeToJSON(json: any): PrivateOrdersGet200ResponseInnerFee {
    return PrivateOrdersGet200ResponseInnerFeeToJSONTyped(json, false);
}

export function PrivateOrdersGet200ResponseInnerFeeToJSONTyped(value?: PrivateOrdersGet200ResponseInnerFee | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'cost': value['cost'],
        'rate': value['rate'],
    };
}

