/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrivateWithdrawalsFinishPostRequest
 */
export interface PrivateWithdrawalsFinishPostRequest {
    /**
     * 
     * @type {string}
     * @memberof PrivateWithdrawalsFinishPostRequest
     */
    payload: string;
}

/**
 * Check if a given object implements the PrivateWithdrawalsFinishPostRequest interface.
 */
export function instanceOfPrivateWithdrawalsFinishPostRequest(value: object): value is PrivateWithdrawalsFinishPostRequest {
    if (!('payload' in value) || value['payload'] === undefined) return false;
    return true;
}

export function PrivateWithdrawalsFinishPostRequestFromJSON(json: any): PrivateWithdrawalsFinishPostRequest {
    return PrivateWithdrawalsFinishPostRequestFromJSONTyped(json, false);
}

export function PrivateWithdrawalsFinishPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivateWithdrawalsFinishPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'payload': json['payload'],
    };
}

export function PrivateWithdrawalsFinishPostRequestToJSON(json: any): PrivateWithdrawalsFinishPostRequest {
    return PrivateWithdrawalsFinishPostRequestToJSONTyped(json, false);
}

export function PrivateWithdrawalsFinishPostRequestToJSONTyped(value?: PrivateWithdrawalsFinishPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payload': value['payload'],
    };
}

