/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PrivateOrdersGet200ResponseInnerFee } from './PrivateOrdersGet200ResponseInnerFee';
import {
    PrivateOrdersGet200ResponseInnerFeeFromJSON,
    PrivateOrdersGet200ResponseInnerFeeFromJSONTyped,
    PrivateOrdersGet200ResponseInnerFeeToJSON,
    PrivateOrdersGet200ResponseInnerFeeToJSONTyped,
} from './PrivateOrdersGet200ResponseInnerFee';

/**
 * 
 * @export
 * @interface PrivateOrdersGet200ResponseInner
 */
export interface PrivateOrdersGet200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof PrivateOrdersGet200ResponseInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PrivateOrdersGet200ResponseInner
     */
    symbol: string;
    /**
     * 
     * @type {string}
     * @memberof PrivateOrdersGet200ResponseInner
     */
    type: PrivateOrdersGet200ResponseInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PrivateOrdersGet200ResponseInner
     */
    side: PrivateOrdersGet200ResponseInnerSideEnum;
    /**
     * 
     * @type {string}
     * @memberof PrivateOrdersGet200ResponseInner
     */
    status: PrivateOrdersGet200ResponseInnerStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof PrivateOrdersGet200ResponseInner
     */
    price: string;
    /**
     * 
     * @type {string}
     * @memberof PrivateOrdersGet200ResponseInner
     */
    average: string;
    /**
     * 
     * @type {string}
     * @memberof PrivateOrdersGet200ResponseInner
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof PrivateOrdersGet200ResponseInner
     */
    filled: string;
    /**
     * 
     * @type {string}
     * @memberof PrivateOrdersGet200ResponseInner
     */
    remaining: string;
    /**
     * 
     * @type {string}
     * @memberof PrivateOrdersGet200ResponseInner
     */
    cost: string;
    /**
     * 
     * @type {PrivateOrdersGet200ResponseInnerFee}
     * @memberof PrivateOrdersGet200ResponseInner
     */
    fee: PrivateOrdersGet200ResponseInnerFee;
    /**
     * 
     * @type {number}
     * @memberof PrivateOrdersGet200ResponseInner
     */
    createdAt: number;
    /**
     * 
     * @type {number}
     * @memberof PrivateOrdersGet200ResponseInner
     */
    updatedAt: number;
    /**
     * 
     * @type {string}
     * @memberof PrivateOrdersGet200ResponseInner
     */
    clientOrderId?: string;
}


/**
 * @export
 */
export const PrivateOrdersGet200ResponseInnerTypeEnum = {
    Market: 'market',
    Limit: 'limit'
} as const;
export type PrivateOrdersGet200ResponseInnerTypeEnum = typeof PrivateOrdersGet200ResponseInnerTypeEnum[keyof typeof PrivateOrdersGet200ResponseInnerTypeEnum];

/**
 * @export
 */
export const PrivateOrdersGet200ResponseInnerSideEnum = {
    Buy: 'buy',
    Sell: 'sell'
} as const;
export type PrivateOrdersGet200ResponseInnerSideEnum = typeof PrivateOrdersGet200ResponseInnerSideEnum[keyof typeof PrivateOrdersGet200ResponseInnerSideEnum];

/**
 * @export
 */
export const PrivateOrdersGet200ResponseInnerStatusEnum = {
    Open: 'open',
    Closed: 'closed',
    Cancelled: 'cancelled'
} as const;
export type PrivateOrdersGet200ResponseInnerStatusEnum = typeof PrivateOrdersGet200ResponseInnerStatusEnum[keyof typeof PrivateOrdersGet200ResponseInnerStatusEnum];


/**
 * Check if a given object implements the PrivateOrdersGet200ResponseInner interface.
 */
export function instanceOfPrivateOrdersGet200ResponseInner(value: object): value is PrivateOrdersGet200ResponseInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('side' in value) || value['side'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('average' in value) || value['average'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('filled' in value) || value['filled'] === undefined) return false;
    if (!('remaining' in value) || value['remaining'] === undefined) return false;
    if (!('cost' in value) || value['cost'] === undefined) return false;
    if (!('fee' in value) || value['fee'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PrivateOrdersGet200ResponseInnerFromJSON(json: any): PrivateOrdersGet200ResponseInner {
    return PrivateOrdersGet200ResponseInnerFromJSONTyped(json, false);
}

export function PrivateOrdersGet200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivateOrdersGet200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'symbol': json['symbol'],
        'type': json['type'],
        'side': json['side'],
        'status': json['status'],
        'price': json['price'],
        'average': json['average'],
        'amount': json['amount'],
        'filled': json['filled'],
        'remaining': json['remaining'],
        'cost': json['cost'],
        'fee': PrivateOrdersGet200ResponseInnerFeeFromJSON(json['fee']),
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
        'clientOrderId': json['client_order_id'] == null ? undefined : json['client_order_id'],
    };
}

export function PrivateOrdersGet200ResponseInnerToJSON(json: any): PrivateOrdersGet200ResponseInner {
    return PrivateOrdersGet200ResponseInnerToJSONTyped(json, false);
}

export function PrivateOrdersGet200ResponseInnerToJSONTyped(value?: PrivateOrdersGet200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'symbol': value['symbol'],
        'type': value['type'],
        'side': value['side'],
        'status': value['status'],
        'price': value['price'],
        'average': value['average'],
        'amount': value['amount'],
        'filled': value['filled'],
        'remaining': value['remaining'],
        'cost': value['cost'],
        'fee': PrivateOrdersGet200ResponseInnerFeeToJSON(value['fee']),
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
        'client_order_id': value['clientOrderId'],
    };
}

