/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrivateBalancesGet200Response
 */
export interface PrivateBalancesGet200Response {
    /**
     * 
     * @type {{ [key: string]: string | undefined; }}
     * @memberof PrivateBalancesGet200Response
     */
    free: { [key: string]: string | undefined; };
    /**
     * 
     * @type {{ [key: string]: string | undefined; }}
     * @memberof PrivateBalancesGet200Response
     */
    locked: { [key: string]: string | undefined; };
}

/**
 * Check if a given object implements the PrivateBalancesGet200Response interface.
 */
export function instanceOfPrivateBalancesGet200Response(value: object): value is PrivateBalancesGet200Response {
    if (!('free' in value) || value['free'] === undefined) return false;
    if (!('locked' in value) || value['locked'] === undefined) return false;
    return true;
}

export function PrivateBalancesGet200ResponseFromJSON(json: any): PrivateBalancesGet200Response {
    return PrivateBalancesGet200ResponseFromJSONTyped(json, false);
}

export function PrivateBalancesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivateBalancesGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'free': json['free'],
        'locked': json['locked'],
    };
}

export function PrivateBalancesGet200ResponseToJSON(json: any): PrivateBalancesGet200Response {
    return PrivateBalancesGet200ResponseToJSONTyped(json, false);
}

export function PrivateBalancesGet200ResponseToJSONTyped(value?: PrivateBalancesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'free': value['free'],
        'locked': value['locked'],
    };
}

