/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicFundsTransparencyGet200ResponseFundsValueValue
 */
export interface PublicFundsTransparencyGet200ResponseFundsValueValue {
    /**
     * 
     * @type {number}
     * @memberof PublicFundsTransparencyGet200ResponseFundsValueValue
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof PublicFundsTransparencyGet200ResponseFundsValueValue
     */
    inCold: number;
    /**
     * 
     * @type {number}
     * @memberof PublicFundsTransparencyGet200ResponseFundsValueValue
     */
    free: number;
    /**
     * 
     * @type {number}
     * @memberof PublicFundsTransparencyGet200ResponseFundsValueValue
     */
    locked: number;
    /**
     * 
     * @type {number}
     * @memberof PublicFundsTransparencyGet200ResponseFundsValueValue
     */
    addressCount: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof PublicFundsTransparencyGet200ResponseFundsValueValue
     */
    addresses: Array<string>;
}

/**
 * Check if a given object implements the PublicFundsTransparencyGet200ResponseFundsValueValue interface.
 */
export function instanceOfPublicFundsTransparencyGet200ResponseFundsValueValue(value: object): value is PublicFundsTransparencyGet200ResponseFundsValueValue {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('inCold' in value) || value['inCold'] === undefined) return false;
    if (!('free' in value) || value['free'] === undefined) return false;
    if (!('locked' in value) || value['locked'] === undefined) return false;
    if (!('addressCount' in value) || value['addressCount'] === undefined) return false;
    if (!('addresses' in value) || value['addresses'] === undefined) return false;
    return true;
}

export function PublicFundsTransparencyGet200ResponseFundsValueValueFromJSON(json: any): PublicFundsTransparencyGet200ResponseFundsValueValue {
    return PublicFundsTransparencyGet200ResponseFundsValueValueFromJSONTyped(json, false);
}

export function PublicFundsTransparencyGet200ResponseFundsValueValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicFundsTransparencyGet200ResponseFundsValueValue {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'inCold': json['in_cold'],
        'free': json['free'],
        'locked': json['locked'],
        'addressCount': json['address_count'],
        'addresses': json['addresses'],
    };
}

export function PublicFundsTransparencyGet200ResponseFundsValueValueToJSON(json: any): PublicFundsTransparencyGet200ResponseFundsValueValue {
    return PublicFundsTransparencyGet200ResponseFundsValueValueToJSONTyped(json, false);
}

export function PublicFundsTransparencyGet200ResponseFundsValueValueToJSONTyped(value?: PublicFundsTransparencyGet200ResponseFundsValueValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'in_cold': value['inCold'],
        'free': value['free'],
        'locked': value['locked'],
        'address_count': value['addressCount'],
        'addresses': value['addresses'],
    };
}

