/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicForexPricesGet200Response
 */
export interface PublicForexPricesGet200Response {
    /**
     * 
     * @type {{ [key: string]: number | undefined; }}
     * @memberof PublicForexPricesGet200Response
     */
    pricesUsd: { [key: string]: number | undefined; };
    /**
     * 
     * @type {{ [key: string]: string | undefined; }}
     * @memberof PublicForexPricesGet200Response
     */
    symbToName: { [key: string]: string | undefined; };
}

/**
 * Check if a given object implements the PublicForexPricesGet200Response interface.
 */
export function instanceOfPublicForexPricesGet200Response(value: object): value is PublicForexPricesGet200Response {
    if (!('pricesUsd' in value) || value['pricesUsd'] === undefined) return false;
    if (!('symbToName' in value) || value['symbToName'] === undefined) return false;
    return true;
}

export function PublicForexPricesGet200ResponseFromJSON(json: any): PublicForexPricesGet200Response {
    return PublicForexPricesGet200ResponseFromJSONTyped(json, false);
}

export function PublicForexPricesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicForexPricesGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'pricesUsd': json['prices_usd'],
        'symbToName': json['symb_to_name'],
    };
}

export function PublicForexPricesGet200ResponseToJSON(json: any): PublicForexPricesGet200Response {
    return PublicForexPricesGet200ResponseToJSONTyped(json, false);
}

export function PublicForexPricesGet200ResponseToJSONTyped(value?: PublicForexPricesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prices_usd': value['pricesUsd'],
        'symb_to_name': value['symbToName'],
    };
}

