/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicPoolsGet200ResponseInnerEarned24h
 */
export interface PublicPoolsGet200ResponseInnerEarned24h {
    /**
     * 
     * @type {string}
     * @memberof PublicPoolsGet200ResponseInnerEarned24h
     */
    base: string;
    /**
     * 
     * @type {string}
     * @memberof PublicPoolsGet200ResponseInnerEarned24h
     */
    quote: string;
}

/**
 * Check if a given object implements the PublicPoolsGet200ResponseInnerEarned24h interface.
 */
export function instanceOfPublicPoolsGet200ResponseInnerEarned24h(value: object): value is PublicPoolsGet200ResponseInnerEarned24h {
    if (!('base' in value) || value['base'] === undefined) return false;
    if (!('quote' in value) || value['quote'] === undefined) return false;
    return true;
}

export function PublicPoolsGet200ResponseInnerEarned24hFromJSON(json: any): PublicPoolsGet200ResponseInnerEarned24h {
    return PublicPoolsGet200ResponseInnerEarned24hFromJSONTyped(json, false);
}

export function PublicPoolsGet200ResponseInnerEarned24hFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicPoolsGet200ResponseInnerEarned24h {
    if (json == null) {
        return json;
    }
    return {
        
        'base': json['base'],
        'quote': json['quote'],
    };
}

export function PublicPoolsGet200ResponseInnerEarned24hToJSON(json: any): PublicPoolsGet200ResponseInnerEarned24h {
    return PublicPoolsGet200ResponseInnerEarned24hToJSONTyped(json, false);
}

export function PublicPoolsGet200ResponseInnerEarned24hToJSONTyped(value?: PublicPoolsGet200ResponseInnerEarned24h | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base': value['base'],
        'quote': value['quote'],
    };
}

