/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PrivatePoolPositionsGet200ResponseInner } from './PrivatePoolPositionsGet200ResponseInner';
import {
    PrivatePoolPositionsGet200ResponseInnerFromJSON,
    PrivatePoolPositionsGet200ResponseInnerFromJSONTyped,
    PrivatePoolPositionsGet200ResponseInnerToJSON,
    PrivatePoolPositionsGet200ResponseInnerToJSONTyped,
} from './PrivatePoolPositionsGet200ResponseInner';

/**
 * 
 * @export
 * @interface PublicPoolStateGet200Response
 */
export interface PublicPoolStateGet200Response {
    /**
     * 
     * @type {string}
     * @memberof PublicPoolStateGet200Response
     */
    baseBalance: string;
    /**
     * 
     * @type {string}
     * @memberof PublicPoolStateGet200Response
     */
    quoteBalance: string;
    /**
     * 
     * @type {string}
     * @memberof PublicPoolStateGet200Response
     */
    currentPrice: string;
    /**
     * 
     * @type {Array<PrivatePoolPositionsGet200ResponseInner>}
     * @memberof PublicPoolStateGet200Response
     */
    positions: Array<PrivatePoolPositionsGet200ResponseInner>;
}

/**
 * Check if a given object implements the PublicPoolStateGet200Response interface.
 */
export function instanceOfPublicPoolStateGet200Response(value: object): value is PublicPoolStateGet200Response {
    if (!('baseBalance' in value) || value['baseBalance'] === undefined) return false;
    if (!('quoteBalance' in value) || value['quoteBalance'] === undefined) return false;
    if (!('currentPrice' in value) || value['currentPrice'] === undefined) return false;
    if (!('positions' in value) || value['positions'] === undefined) return false;
    return true;
}

export function PublicPoolStateGet200ResponseFromJSON(json: any): PublicPoolStateGet200Response {
    return PublicPoolStateGet200ResponseFromJSONTyped(json, false);
}

export function PublicPoolStateGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicPoolStateGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'baseBalance': json['base_balance'],
        'quoteBalance': json['quote_balance'],
        'currentPrice': json['current_price'],
        'positions': ((json['positions'] as Array<any>).map(PrivatePoolPositionsGet200ResponseInnerFromJSON)),
    };
}

export function PublicPoolStateGet200ResponseToJSON(json: any): PublicPoolStateGet200Response {
    return PublicPoolStateGet200ResponseToJSONTyped(json, false);
}

export function PublicPoolStateGet200ResponseToJSONTyped(value?: PublicPoolStateGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base_balance': value['baseBalance'],
        'quote_balance': value['quoteBalance'],
        'current_price': value['currentPrice'],
        'positions': ((value['positions'] as Array<any>).map(PrivatePoolPositionsGet200ResponseInnerToJSON)),
    };
}

