/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicOhlcvGet200ResponseInner
 */
export interface PublicOhlcvGet200ResponseInner {
    /**
     * 
     * @type {number}
     * @memberof PublicOhlcvGet200ResponseInner
     */
    time: number;
    /**
     * 
     * @type {string}
     * @memberof PublicOhlcvGet200ResponseInner
     */
    open: string;
    /**
     * 
     * @type {string}
     * @memberof PublicOhlcvGet200ResponseInner
     */
    high: string;
    /**
     * 
     * @type {string}
     * @memberof PublicOhlcvGet200ResponseInner
     */
    low: string;
    /**
     * 
     * @type {string}
     * @memberof PublicOhlcvGet200ResponseInner
     */
    close: string;
    /**
     * 
     * @type {string}
     * @memberof PublicOhlcvGet200ResponseInner
     */
    volume: string;
}

/**
 * Check if a given object implements the PublicOhlcvGet200ResponseInner interface.
 */
export function instanceOfPublicOhlcvGet200ResponseInner(value: object): value is PublicOhlcvGet200ResponseInner {
    if (!('time' in value) || value['time'] === undefined) return false;
    if (!('open' in value) || value['open'] === undefined) return false;
    if (!('high' in value) || value['high'] === undefined) return false;
    if (!('low' in value) || value['low'] === undefined) return false;
    if (!('close' in value) || value['close'] === undefined) return false;
    if (!('volume' in value) || value['volume'] === undefined) return false;
    return true;
}

export function PublicOhlcvGet200ResponseInnerFromJSON(json: any): PublicOhlcvGet200ResponseInner {
    return PublicOhlcvGet200ResponseInnerFromJSONTyped(json, false);
}

export function PublicOhlcvGet200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicOhlcvGet200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'time': json['time'],
        'open': json['open'],
        'high': json['high'],
        'low': json['low'],
        'close': json['close'],
        'volume': json['volume'],
    };
}

export function PublicOhlcvGet200ResponseInnerToJSON(json: any): PublicOhlcvGet200ResponseInner {
    return PublicOhlcvGet200ResponseInnerToJSONTyped(json, false);
}

export function PublicOhlcvGet200ResponseInnerToJSONTyped(value?: PublicOhlcvGet200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time': value['time'],
        'open': value['open'],
        'high': value['high'],
        'low': value['low'],
        'close': value['close'],
        'volume': value['volume'],
    };
}

