/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicExkConfigGet200ResponseRoutesValueLogsInner
 */
export interface PublicExkConfigGet200ResponseRoutesValueLogsInner {
    /**
     * 
     * @type {number}
     * @memberof PublicExkConfigGet200ResponseRoutesValueLogsInner
     */
    t: number;
    /**
     * 
     * @type {string}
     * @memberof PublicExkConfigGet200ResponseRoutesValueLogsInner
     */
    v: string;
}

/**
 * Check if a given object implements the PublicExkConfigGet200ResponseRoutesValueLogsInner interface.
 */
export function instanceOfPublicExkConfigGet200ResponseRoutesValueLogsInner(value: object): value is PublicExkConfigGet200ResponseRoutesValueLogsInner {
    if (!('t' in value) || value['t'] === undefined) return false;
    if (!('v' in value) || value['v'] === undefined) return false;
    return true;
}

export function PublicExkConfigGet200ResponseRoutesValueLogsInnerFromJSON(json: any): PublicExkConfigGet200ResponseRoutesValueLogsInner {
    return PublicExkConfigGet200ResponseRoutesValueLogsInnerFromJSONTyped(json, false);
}

export function PublicExkConfigGet200ResponseRoutesValueLogsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicExkConfigGet200ResponseRoutesValueLogsInner {
    if (json == null) {
        return json;
    }
    return {
        
        't': json['t'],
        'v': json['v'],
    };
}

export function PublicExkConfigGet200ResponseRoutesValueLogsInnerToJSON(json: any): PublicExkConfigGet200ResponseRoutesValueLogsInner {
    return PublicExkConfigGet200ResponseRoutesValueLogsInnerToJSONTyped(json, false);
}

export function PublicExkConfigGet200ResponseRoutesValueLogsInnerToJSONTyped(value?: PublicExkConfigGet200ResponseRoutesValueLogsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        't': value['t'],
        'v': value['v'],
    };
}

