/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicOrderbookGet200Response
 */
export interface PublicOrderbookGet200Response {
    /**
     * 
     * @type {Array<Array<string>>}
     * @memberof PublicOrderbookGet200Response
     */
    bids: Array<Array<string>>;
    /**
     * 
     * @type {Array<Array<string>>}
     * @memberof PublicOrderbookGet200Response
     */
    asks: Array<Array<string>>;
    /**
     * 
     * @type {number}
     * @memberof PublicOrderbookGet200Response
     */
    timestamp: number;
}

/**
 * Check if a given object implements the PublicOrderbookGet200Response interface.
 */
export function instanceOfPublicOrderbookGet200Response(value: object): value is PublicOrderbookGet200Response {
    if (!('bids' in value) || value['bids'] === undefined) return false;
    if (!('asks' in value) || value['asks'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function PublicOrderbookGet200ResponseFromJSON(json: any): PublicOrderbookGet200Response {
    return PublicOrderbookGet200ResponseFromJSONTyped(json, false);
}

export function PublicOrderbookGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicOrderbookGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'bids': json['bids'],
        'asks': json['asks'],
        'timestamp': json['timestamp'],
    };
}

export function PublicOrderbookGet200ResponseToJSON(json: any): PublicOrderbookGet200Response {
    return PublicOrderbookGet200ResponseToJSONTyped(json, false);
}

export function PublicOrderbookGet200ResponseToJSONTyped(value?: PublicOrderbookGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bids': value['bids'],
        'asks': value['asks'],
        'timestamp': value['timestamp'],
    };
}

