/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicGainsLossesTransparencyGet200ResponseLast20Inner } from './PublicGainsLossesTransparencyGet200ResponseLast20Inner';
import {
    PublicGainsLossesTransparencyGet200ResponseLast20InnerFromJSON,
    PublicGainsLossesTransparencyGet200ResponseLast20InnerFromJSONTyped,
    PublicGainsLossesTransparencyGet200ResponseLast20InnerToJSON,
    PublicGainsLossesTransparencyGet200ResponseLast20InnerToJSONTyped,
} from './PublicGainsLossesTransparencyGet200ResponseLast20Inner';
import type { PublicGainsLossesTransparencyGet200ResponseCurrenciesValue } from './PublicGainsLossesTransparencyGet200ResponseCurrenciesValue';
import {
    PublicGainsLossesTransparencyGet200ResponseCurrenciesValueFromJSON,
    PublicGainsLossesTransparencyGet200ResponseCurrenciesValueFromJSONTyped,
    PublicGainsLossesTransparencyGet200ResponseCurrenciesValueToJSON,
    PublicGainsLossesTransparencyGet200ResponseCurrenciesValueToJSONTyped,
} from './PublicGainsLossesTransparencyGet200ResponseCurrenciesValue';

/**
 * 
 * @export
 * @interface PublicGainsLossesTransparencyGet200Response
 */
export interface PublicGainsLossesTransparencyGet200Response {
    /**
     * 
     * @type {number}
     * @memberof PublicGainsLossesTransparencyGet200Response
     */
    timestamp: number;
    /**
     * 
     * @type {{ [key: string]: PublicGainsLossesTransparencyGet200ResponseCurrenciesValue | undefined; }}
     * @memberof PublicGainsLossesTransparencyGet200Response
     */
    currencies: { [key: string]: PublicGainsLossesTransparencyGet200ResponseCurrenciesValue | undefined; };
    /**
     * 
     * @type {Array<PublicGainsLossesTransparencyGet200ResponseLast20Inner>}
     * @memberof PublicGainsLossesTransparencyGet200Response
     */
    last20: Array<PublicGainsLossesTransparencyGet200ResponseLast20Inner>;
}

/**
 * Check if a given object implements the PublicGainsLossesTransparencyGet200Response interface.
 */
export function instanceOfPublicGainsLossesTransparencyGet200Response(value: object): value is PublicGainsLossesTransparencyGet200Response {
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('currencies' in value) || value['currencies'] === undefined) return false;
    if (!('last20' in value) || value['last20'] === undefined) return false;
    return true;
}

export function PublicGainsLossesTransparencyGet200ResponseFromJSON(json: any): PublicGainsLossesTransparencyGet200Response {
    return PublicGainsLossesTransparencyGet200ResponseFromJSONTyped(json, false);
}

export function PublicGainsLossesTransparencyGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicGainsLossesTransparencyGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'],
        'currencies': (mapValues(json['currencies'], PublicGainsLossesTransparencyGet200ResponseCurrenciesValueFromJSON)),
        'last20': ((json['last_20'] as Array<any>).map(PublicGainsLossesTransparencyGet200ResponseLast20InnerFromJSON)),
    };
}

export function PublicGainsLossesTransparencyGet200ResponseToJSON(json: any): PublicGainsLossesTransparencyGet200Response {
    return PublicGainsLossesTransparencyGet200ResponseToJSONTyped(json, false);
}

export function PublicGainsLossesTransparencyGet200ResponseToJSONTyped(value?: PublicGainsLossesTransparencyGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'],
        'currencies': (mapValues(value['currencies'], PublicGainsLossesTransparencyGet200ResponseCurrenciesValueToJSON)),
        'last_20': ((value['last20'] as Array<any>).map(PublicGainsLossesTransparencyGet200ResponseLast20InnerToJSON)),
    };
}

