/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicCurrenciesGet200ResponseInnerNetworksInner
 */
export interface PublicCurrenciesGet200ResponseInnerNetworksInner {
    /**
     * 
     * @type {string}
     * @memberof PublicCurrenciesGet200ResponseInnerNetworksInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PublicCurrenciesGet200ResponseInnerNetworksInner
     */
    contractAddress?: string;
}

/**
 * Check if a given object implements the PublicCurrenciesGet200ResponseInnerNetworksInner interface.
 */
export function instanceOfPublicCurrenciesGet200ResponseInnerNetworksInner(value: object): value is PublicCurrenciesGet200ResponseInnerNetworksInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function PublicCurrenciesGet200ResponseInnerNetworksInnerFromJSON(json: any): PublicCurrenciesGet200ResponseInnerNetworksInner {
    return PublicCurrenciesGet200ResponseInnerNetworksInnerFromJSONTyped(json, false);
}

export function PublicCurrenciesGet200ResponseInnerNetworksInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicCurrenciesGet200ResponseInnerNetworksInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'contractAddress': json['contract_address'] == null ? undefined : json['contract_address'],
    };
}

export function PublicCurrenciesGet200ResponseInnerNetworksInnerToJSON(json: any): PublicCurrenciesGet200ResponseInnerNetworksInner {
    return PublicCurrenciesGet200ResponseInnerNetworksInnerToJSONTyped(json, false);
}

export function PublicCurrenciesGet200ResponseInnerNetworksInnerToJSONTyped(value?: PublicCurrenciesGet200ResponseInnerNetworksInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'contract_address': value['contractAddress'],
    };
}

