/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicTradesGet200ResponseInner
 */
export interface PublicTradesGet200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof PublicTradesGet200ResponseInner
     */
    side: string;
    /**
     * 
     * @type {string}
     * @memberof PublicTradesGet200ResponseInner
     */
    price: string;
    /**
     * 
     * @type {string}
     * @memberof PublicTradesGet200ResponseInner
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof PublicTradesGet200ResponseInner
     */
    cost: string;
    /**
     * 
     * @type {number}
     * @memberof PublicTradesGet200ResponseInner
     */
    createdAt: number;
}

/**
 * Check if a given object implements the PublicTradesGet200ResponseInner interface.
 */
export function instanceOfPublicTradesGet200ResponseInner(value: object): value is PublicTradesGet200ResponseInner {
    if (!('side' in value) || value['side'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('cost' in value) || value['cost'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function PublicTradesGet200ResponseInnerFromJSON(json: any): PublicTradesGet200ResponseInner {
    return PublicTradesGet200ResponseInnerFromJSONTyped(json, false);
}

export function PublicTradesGet200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicTradesGet200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'side': json['side'],
        'price': json['price'],
        'amount': json['amount'],
        'cost': json['cost'],
        'createdAt': json['created_at'],
    };
}

export function PublicTradesGet200ResponseInnerToJSON(json: any): PublicTradesGet200ResponseInner {
    return PublicTradesGet200ResponseInnerToJSONTyped(json, false);
}

export function PublicTradesGet200ResponseInnerToJSONTyped(value?: PublicTradesGet200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'side': value['side'],
        'price': value['price'],
        'amount': value['amount'],
        'cost': value['cost'],
        'created_at': value['createdAt'],
    };
}

