/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicMarketsGet200ResponseInnerLimitsPrice
 */
export interface PublicMarketsGet200ResponseInnerLimitsPrice {
    /**
     * 
     * @type {string}
     * @memberof PublicMarketsGet200ResponseInnerLimitsPrice
     */
    min?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicMarketsGet200ResponseInnerLimitsPrice
     */
    max?: string;
}

/**
 * Check if a given object implements the PublicMarketsGet200ResponseInnerLimitsPrice interface.
 */
export function instanceOfPublicMarketsGet200ResponseInnerLimitsPrice(value: object): value is PublicMarketsGet200ResponseInnerLimitsPrice {
    return true;
}

export function PublicMarketsGet200ResponseInnerLimitsPriceFromJSON(json: any): PublicMarketsGet200ResponseInnerLimitsPrice {
    return PublicMarketsGet200ResponseInnerLimitsPriceFromJSONTyped(json, false);
}

export function PublicMarketsGet200ResponseInnerLimitsPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicMarketsGet200ResponseInnerLimitsPrice {
    if (json == null) {
        return json;
    }
    return {
        
        'min': json['min'] == null ? undefined : json['min'],
        'max': json['max'] == null ? undefined : json['max'],
    };
}

export function PublicMarketsGet200ResponseInnerLimitsPriceToJSON(json: any): PublicMarketsGet200ResponseInnerLimitsPrice {
    return PublicMarketsGet200ResponseInnerLimitsPriceToJSONTyped(json, false);
}

export function PublicMarketsGet200ResponseInnerLimitsPriceToJSONTyped(value?: PublicMarketsGet200ResponseInnerLimitsPrice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'min': value['min'],
        'max': value['max'],
    };
}

