/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicExkConfigGet200ResponseUserLevelsInner } from './PublicExkConfigGet200ResponseUserLevelsInner';
import {
    PublicExkConfigGet200ResponseUserLevelsInnerFromJSON,
    PublicExkConfigGet200ResponseUserLevelsInnerFromJSONTyped,
    PublicExkConfigGet200ResponseUserLevelsInnerToJSON,
    PublicExkConfigGet200ResponseUserLevelsInnerToJSONTyped,
} from './PublicExkConfigGet200ResponseUserLevelsInner';
import type { PublicExkConfigGet200ResponseWeeklyDist } from './PublicExkConfigGet200ResponseWeeklyDist';
import {
    PublicExkConfigGet200ResponseWeeklyDistFromJSON,
    PublicExkConfigGet200ResponseWeeklyDistFromJSONTyped,
    PublicExkConfigGet200ResponseWeeklyDistToJSON,
    PublicExkConfigGet200ResponseWeeklyDistToJSONTyped,
} from './PublicExkConfigGet200ResponseWeeklyDist';
import type { PublicExkConfigGet200ResponseRoutesValue } from './PublicExkConfigGet200ResponseRoutesValue';
import {
    PublicExkConfigGet200ResponseRoutesValueFromJSON,
    PublicExkConfigGet200ResponseRoutesValueFromJSONTyped,
    PublicExkConfigGet200ResponseRoutesValueToJSON,
    PublicExkConfigGet200ResponseRoutesValueToJSONTyped,
} from './PublicExkConfigGet200ResponseRoutesValue';

/**
 * 
 * @export
 * @interface PublicExkConfigGet200Response
 */
export interface PublicExkConfigGet200Response {
    /**
     * 
     * @type {number}
     * @memberof PublicExkConfigGet200Response
     */
    circulatingSupply: number;
    /**
     * 
     * @type {number}
     * @memberof PublicExkConfigGet200Response
     */
    lastReserveValueUsd: number;
    /**
     * 
     * @type {number}
     * @memberof PublicExkConfigGet200Response
     */
    mintRate: number;
    /**
     * 
     * @type {number}
     * @memberof PublicExkConfigGet200Response
     */
    lpSharePercentToExk: number;
    /**
     * 
     * @type {{ [key: string]: PublicExkConfigGet200ResponseRoutesValue | undefined; }}
     * @memberof PublicExkConfigGet200Response
     */
    routes: { [key: string]: PublicExkConfigGet200ResponseRoutesValue | undefined; };
    /**
     * 
     * @type {Array<PublicExkConfigGet200ResponseUserLevelsInner>}
     * @memberof PublicExkConfigGet200Response
     */
    userLevels: Array<PublicExkConfigGet200ResponseUserLevelsInner>;
    /**
     * 
     * @type {PublicExkConfigGet200ResponseWeeklyDist}
     * @memberof PublicExkConfigGet200Response
     */
    weeklyDist: PublicExkConfigGet200ResponseWeeklyDist;
}

/**
 * Check if a given object implements the PublicExkConfigGet200Response interface.
 */
export function instanceOfPublicExkConfigGet200Response(value: object): value is PublicExkConfigGet200Response {
    if (!('circulatingSupply' in value) || value['circulatingSupply'] === undefined) return false;
    if (!('lastReserveValueUsd' in value) || value['lastReserveValueUsd'] === undefined) return false;
    if (!('mintRate' in value) || value['mintRate'] === undefined) return false;
    if (!('lpSharePercentToExk' in value) || value['lpSharePercentToExk'] === undefined) return false;
    if (!('routes' in value) || value['routes'] === undefined) return false;
    if (!('userLevels' in value) || value['userLevels'] === undefined) return false;
    if (!('weeklyDist' in value) || value['weeklyDist'] === undefined) return false;
    return true;
}

export function PublicExkConfigGet200ResponseFromJSON(json: any): PublicExkConfigGet200Response {
    return PublicExkConfigGet200ResponseFromJSONTyped(json, false);
}

export function PublicExkConfigGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicExkConfigGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'circulatingSupply': json['circulating_supply'],
        'lastReserveValueUsd': json['last_reserve_value_usd'],
        'mintRate': json['mint_rate'],
        'lpSharePercentToExk': json['lp_share_percent_to_exk'],
        'routes': (mapValues(json['routes'], PublicExkConfigGet200ResponseRoutesValueFromJSON)),
        'userLevels': ((json['user_levels'] as Array<any>).map(PublicExkConfigGet200ResponseUserLevelsInnerFromJSON)),
        'weeklyDist': PublicExkConfigGet200ResponseWeeklyDistFromJSON(json['weekly_dist']),
    };
}

export function PublicExkConfigGet200ResponseToJSON(json: any): PublicExkConfigGet200Response {
    return PublicExkConfigGet200ResponseToJSONTyped(json, false);
}

export function PublicExkConfigGet200ResponseToJSONTyped(value?: PublicExkConfigGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'circulating_supply': value['circulatingSupply'],
        'last_reserve_value_usd': value['lastReserveValueUsd'],
        'mint_rate': value['mintRate'],
        'lp_share_percent_to_exk': value['lpSharePercentToExk'],
        'routes': (mapValues(value['routes'], PublicExkConfigGet200ResponseRoutesValueToJSON)),
        'user_levels': ((value['userLevels'] as Array<any>).map(PublicExkConfigGet200ResponseUserLevelsInnerToJSON)),
        'weekly_dist': PublicExkConfigGet200ResponseWeeklyDistToJSON(value['weeklyDist']),
    };
}

