/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicPoolsGet200ResponseInnerEarned24h } from './PublicPoolsGet200ResponseInnerEarned24h';
import {
    PublicPoolsGet200ResponseInnerEarned24hFromJSON,
    PublicPoolsGet200ResponseInnerEarned24hFromJSONTyped,
    PublicPoolsGet200ResponseInnerEarned24hToJSON,
    PublicPoolsGet200ResponseInnerEarned24hToJSONTyped,
} from './PublicPoolsGet200ResponseInnerEarned24h';

/**
 * 
 * @export
 * @interface PublicPoolsGet200ResponseInner
 */
export interface PublicPoolsGet200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof PublicPoolsGet200ResponseInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PublicPoolsGet200ResponseInner
     */
    baseCurrency: string;
    /**
     * 
     * @type {string}
     * @memberof PublicPoolsGet200ResponseInner
     */
    quoteCurrency: string;
    /**
     * 
     * @type {string}
     * @memberof PublicPoolsGet200ResponseInner
     */
    baseReserve: string;
    /**
     * 
     * @type {string}
     * @memberof PublicPoolsGet200ResponseInner
     */
    quoteReserve: string;
    /**
     * 
     * @type {string}
     * @memberof PublicPoolsGet200ResponseInner
     */
    price: string;
    /**
     * 
     * @type {PublicPoolsGet200ResponseInnerEarned24h}
     * @memberof PublicPoolsGet200ResponseInner
     */
    earned24h: PublicPoolsGet200ResponseInnerEarned24h;
    /**
     * 
     * @type {string}
     * @memberof PublicPoolsGet200ResponseInner
     */
    aPYEstimatedOnFees24h: string;
    /**
     * 
     * @type {any}
     * @memberof PublicPoolsGet200ResponseInner
     */
    active?: any | null;
}

/**
 * Check if a given object implements the PublicPoolsGet200ResponseInner interface.
 */
export function instanceOfPublicPoolsGet200ResponseInner(value: object): value is PublicPoolsGet200ResponseInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('baseCurrency' in value) || value['baseCurrency'] === undefined) return false;
    if (!('quoteCurrency' in value) || value['quoteCurrency'] === undefined) return false;
    if (!('baseReserve' in value) || value['baseReserve'] === undefined) return false;
    if (!('quoteReserve' in value) || value['quoteReserve'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('earned24h' in value) || value['earned24h'] === undefined) return false;
    if (!('aPYEstimatedOnFees24h' in value) || value['aPYEstimatedOnFees24h'] === undefined) return false;
    return true;
}

export function PublicPoolsGet200ResponseInnerFromJSON(json: any): PublicPoolsGet200ResponseInner {
    return PublicPoolsGet200ResponseInnerFromJSONTyped(json, false);
}

export function PublicPoolsGet200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicPoolsGet200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'baseCurrency': json['base_currency'],
        'quoteCurrency': json['quote_currency'],
        'baseReserve': json['base_reserve'],
        'quoteReserve': json['quote_reserve'],
        'price': json['price'],
        'earned24h': PublicPoolsGet200ResponseInnerEarned24hFromJSON(json['earned_24h']),
        'aPYEstimatedOnFees24h': json['APY_estimated_on_fees_24h'],
        'active': json['active'] == null ? undefined : json['active'],
    };
}

export function PublicPoolsGet200ResponseInnerToJSON(json: any): PublicPoolsGet200ResponseInner {
    return PublicPoolsGet200ResponseInnerToJSONTyped(json, false);
}

export function PublicPoolsGet200ResponseInnerToJSONTyped(value?: PublicPoolsGet200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'base_currency': value['baseCurrency'],
        'quote_currency': value['quoteCurrency'],
        'base_reserve': value['baseReserve'],
        'quote_reserve': value['quoteReserve'],
        'price': value['price'],
        'earned_24h': PublicPoolsGet200ResponseInnerEarned24hToJSON(value['earned24h']),
        'APY_estimated_on_fees_24h': value['aPYEstimatedOnFees24h'],
        'active': value['active'],
    };
}

