/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicNetworksGet200ResponseInner
 */
export interface PublicNetworksGet200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof PublicNetworksGet200ResponseInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PublicNetworksGet200ResponseInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PublicNetworksGet200ResponseInner
     */
    chainLike: string;
    /**
     * 
     * @type {number}
     * @memberof PublicNetworksGet200ResponseInner
     */
    withdrawalFeeUsd: number;
    /**
     * 
     * @type {number}
     * @memberof PublicNetworksGet200ResponseInner
     */
    minDepositUsd: number;
    /**
     * 
     * @type {string}
     * @memberof PublicNetworksGet200ResponseInner
     */
    logoUrl: string;
    /**
     * 
     * @type {number}
     * @memberof PublicNetworksGet200ResponseInner
     */
    minConfirmations: number;
    /**
     * 
     * @type {string}
     * @memberof PublicNetworksGet200ResponseInner
     */
    explorerTxid: string;
    /**
     * 
     * @type {string}
     * @memberof PublicNetworksGet200ResponseInner
     */
    explorerAddress: string;
    /**
     * 
     * @type {string}
     * @memberof PublicNetworksGet200ResponseInner
     */
    nativeCurrency: string;
    /**
     * 
     * @type {any}
     * @memberof PublicNetworksGet200ResponseInner
     */
    active?: any | null;
    /**
     * 
     * @type {string}
     * @memberof PublicNetworksGet200ResponseInner
     */
    addressRegex?: string;
    /**
     * 
     * @type {any}
     * @memberof PublicNetworksGet200ResponseInner
     */
    memoSupport?: any | null;
}

/**
 * Check if a given object implements the PublicNetworksGet200ResponseInner interface.
 */
export function instanceOfPublicNetworksGet200ResponseInner(value: object): value is PublicNetworksGet200ResponseInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('chainLike' in value) || value['chainLike'] === undefined) return false;
    if (!('withdrawalFeeUsd' in value) || value['withdrawalFeeUsd'] === undefined) return false;
    if (!('minDepositUsd' in value) || value['minDepositUsd'] === undefined) return false;
    if (!('logoUrl' in value) || value['logoUrl'] === undefined) return false;
    if (!('minConfirmations' in value) || value['minConfirmations'] === undefined) return false;
    if (!('explorerTxid' in value) || value['explorerTxid'] === undefined) return false;
    if (!('explorerAddress' in value) || value['explorerAddress'] === undefined) return false;
    if (!('nativeCurrency' in value) || value['nativeCurrency'] === undefined) return false;
    return true;
}

export function PublicNetworksGet200ResponseInnerFromJSON(json: any): PublicNetworksGet200ResponseInner {
    return PublicNetworksGet200ResponseInnerFromJSONTyped(json, false);
}

export function PublicNetworksGet200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicNetworksGet200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'chainLike': json['chain_like'],
        'withdrawalFeeUsd': json['withdrawal_fee_usd'],
        'minDepositUsd': json['min_deposit_usd'],
        'logoUrl': json['logo_url'],
        'minConfirmations': json['min_confirmations'],
        'explorerTxid': json['explorer_txid'],
        'explorerAddress': json['explorer_address'],
        'nativeCurrency': json['native_currency'],
        'active': json['active'] == null ? undefined : json['active'],
        'addressRegex': json['address_regex'] == null ? undefined : json['address_regex'],
        'memoSupport': json['memo_support'] == null ? undefined : json['memo_support'],
    };
}

export function PublicNetworksGet200ResponseInnerToJSON(json: any): PublicNetworksGet200ResponseInner {
    return PublicNetworksGet200ResponseInnerToJSONTyped(json, false);
}

export function PublicNetworksGet200ResponseInnerToJSONTyped(value?: PublicNetworksGet200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'chain_like': value['chainLike'],
        'withdrawal_fee_usd': value['withdrawalFeeUsd'],
        'min_deposit_usd': value['minDepositUsd'],
        'logo_url': value['logoUrl'],
        'min_confirmations': value['minConfirmations'],
        'explorer_txid': value['explorerTxid'],
        'explorer_address': value['explorerAddress'],
        'native_currency': value['nativeCurrency'],
        'active': value['active'],
        'address_regex': value['addressRegex'],
        'memo_support': value['memoSupport'],
    };
}

