/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicExkConfigGet200ResponseUserLevelsInner
 */
export interface PublicExkConfigGet200ResponseUserLevelsInner {
    /**
     * 
     * @type {number}
     * @memberof PublicExkConfigGet200ResponseUserLevelsInner
     */
    pointsFactor: number;
    /**
     * 
     * @type {string}
     * @memberof PublicExkConfigGet200ResponseUserLevelsInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PublicExkConfigGet200ResponseUserLevelsInner
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof PublicExkConfigGet200ResponseUserLevelsInner
     */
    icon: string;
    /**
     * 
     * @type {number}
     * @memberof PublicExkConfigGet200ResponseUserLevelsInner
     */
    requiredPoints: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof PublicExkConfigGet200ResponseUserLevelsInner
     */
    benefits: Array<string>;
}

/**
 * Check if a given object implements the PublicExkConfigGet200ResponseUserLevelsInner interface.
 */
export function instanceOfPublicExkConfigGet200ResponseUserLevelsInner(value: object): value is PublicExkConfigGet200ResponseUserLevelsInner {
    if (!('pointsFactor' in value) || value['pointsFactor'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    if (!('requiredPoints' in value) || value['requiredPoints'] === undefined) return false;
    if (!('benefits' in value) || value['benefits'] === undefined) return false;
    return true;
}

export function PublicExkConfigGet200ResponseUserLevelsInnerFromJSON(json: any): PublicExkConfigGet200ResponseUserLevelsInner {
    return PublicExkConfigGet200ResponseUserLevelsInnerFromJSONTyped(json, false);
}

export function PublicExkConfigGet200ResponseUserLevelsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicExkConfigGet200ResponseUserLevelsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'pointsFactor': json['points_factor'],
        'name': json['name'],
        'description': json['description'],
        'icon': json['icon'],
        'requiredPoints': json['required_points'],
        'benefits': json['benefits'],
    };
}

export function PublicExkConfigGet200ResponseUserLevelsInnerToJSON(json: any): PublicExkConfigGet200ResponseUserLevelsInner {
    return PublicExkConfigGet200ResponseUserLevelsInnerToJSONTyped(json, false);
}

export function PublicExkConfigGet200ResponseUserLevelsInnerToJSONTyped(value?: PublicExkConfigGet200ResponseUserLevelsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'points_factor': value['pointsFactor'],
        'name': value['name'],
        'description': value['description'],
        'icon': value['icon'],
        'required_points': value['requiredPoints'],
        'benefits': value['benefits'],
    };
}

