/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicFundsTransparencyGet200ResponseStatsValue
 */
export interface PublicFundsTransparencyGet200ResponseStatsValue {
    /**
     * 
     * @type {number}
     * @memberof PublicFundsTransparencyGet200ResponseStatsValue
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof PublicFundsTransparencyGet200ResponseStatsValue
     */
    inCold: number;
    /**
     * 
     * @type {number}
     * @memberof PublicFundsTransparencyGet200ResponseStatsValue
     */
    totalUserOwned: number;
    /**
     * 
     * @type {string}
     * @memberof PublicFundsTransparencyGet200ResponseStatsValue
     */
    reserve: string;
}

/**
 * Check if a given object implements the PublicFundsTransparencyGet200ResponseStatsValue interface.
 */
export function instanceOfPublicFundsTransparencyGet200ResponseStatsValue(value: object): value is PublicFundsTransparencyGet200ResponseStatsValue {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('inCold' in value) || value['inCold'] === undefined) return false;
    if (!('totalUserOwned' in value) || value['totalUserOwned'] === undefined) return false;
    if (!('reserve' in value) || value['reserve'] === undefined) return false;
    return true;
}

export function PublicFundsTransparencyGet200ResponseStatsValueFromJSON(json: any): PublicFundsTransparencyGet200ResponseStatsValue {
    return PublicFundsTransparencyGet200ResponseStatsValueFromJSONTyped(json, false);
}

export function PublicFundsTransparencyGet200ResponseStatsValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicFundsTransparencyGet200ResponseStatsValue {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'inCold': json['in_cold'],
        'totalUserOwned': json['total_user_owned'],
        'reserve': json['reserve'],
    };
}

export function PublicFundsTransparencyGet200ResponseStatsValueToJSON(json: any): PublicFundsTransparencyGet200ResponseStatsValue {
    return PublicFundsTransparencyGet200ResponseStatsValueToJSONTyped(json, false);
}

export function PublicFundsTransparencyGet200ResponseStatsValueToJSONTyped(value?: PublicFundsTransparencyGet200ResponseStatsValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'in_cold': value['inCold'],
        'total_user_owned': value['totalUserOwned'],
        'reserve': value['reserve'],
    };
}

