/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicGainsLossesTransparencyGet200ResponseCurrenciesValue
 */
export interface PublicGainsLossesTransparencyGet200ResponseCurrenciesValue {
    /**
     * 
     * @type {string}
     * @memberof PublicGainsLossesTransparencyGet200ResponseCurrenciesValue
     */
    total: string;
    /**
     * 
     * @type {string}
     * @memberof PublicGainsLossesTransparencyGet200ResponseCurrenciesValue
     */
    trades: string;
    /**
     * 
     * @type {string}
     * @memberof PublicGainsLossesTransparencyGet200ResponseCurrenciesValue
     */
    exkProgram: string;
    /**
     * 
     * @type {string}
     * @memberof PublicGainsLossesTransparencyGet200ResponseCurrenciesValue
     */
    withdrawals: string;
    /**
     * 
     * @type {string}
     * @memberof PublicGainsLossesTransparencyGet200ResponseCurrenciesValue
     */
    transfers: string;
    /**
     * 
     * @type {string}
     * @memberof PublicGainsLossesTransparencyGet200ResponseCurrenciesValue
     */
    adminWithdrawals: string;
    /**
     * 
     * @type {string}
     * @memberof PublicGainsLossesTransparencyGet200ResponseCurrenciesValue
     */
    adminDeposits: string;
}

/**
 * Check if a given object implements the PublicGainsLossesTransparencyGet200ResponseCurrenciesValue interface.
 */
export function instanceOfPublicGainsLossesTransparencyGet200ResponseCurrenciesValue(value: object): value is PublicGainsLossesTransparencyGet200ResponseCurrenciesValue {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('trades' in value) || value['trades'] === undefined) return false;
    if (!('exkProgram' in value) || value['exkProgram'] === undefined) return false;
    if (!('withdrawals' in value) || value['withdrawals'] === undefined) return false;
    if (!('transfers' in value) || value['transfers'] === undefined) return false;
    if (!('adminWithdrawals' in value) || value['adminWithdrawals'] === undefined) return false;
    if (!('adminDeposits' in value) || value['adminDeposits'] === undefined) return false;
    return true;
}

export function PublicGainsLossesTransparencyGet200ResponseCurrenciesValueFromJSON(json: any): PublicGainsLossesTransparencyGet200ResponseCurrenciesValue {
    return PublicGainsLossesTransparencyGet200ResponseCurrenciesValueFromJSONTyped(json, false);
}

export function PublicGainsLossesTransparencyGet200ResponseCurrenciesValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicGainsLossesTransparencyGet200ResponseCurrenciesValue {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'trades': json['trades'],
        'exkProgram': json['exk_program'],
        'withdrawals': json['withdrawals'],
        'transfers': json['transfers'],
        'adminWithdrawals': json['admin_withdrawals'],
        'adminDeposits': json['admin_deposits'],
    };
}

export function PublicGainsLossesTransparencyGet200ResponseCurrenciesValueToJSON(json: any): PublicGainsLossesTransparencyGet200ResponseCurrenciesValue {
    return PublicGainsLossesTransparencyGet200ResponseCurrenciesValueToJSONTyped(json, false);
}

export function PublicGainsLossesTransparencyGet200ResponseCurrenciesValueToJSONTyped(value?: PublicGainsLossesTransparencyGet200ResponseCurrenciesValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'trades': value['trades'],
        'exk_program': value['exkProgram'],
        'withdrawals': value['withdrawals'],
        'transfers': value['transfers'],
        'admin_withdrawals': value['adminWithdrawals'],
        'admin_deposits': value['adminDeposits'],
    };
}

