/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicGainsLossesTransparencyGet200ResponseLast20Inner
 */
export interface PublicGainsLossesTransparencyGet200ResponseLast20Inner {
    /**
     * 
     * @type {string}
     * @memberof PublicGainsLossesTransparencyGet200ResponseLast20Inner
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof PublicGainsLossesTransparencyGet200ResponseLast20Inner
     */
    network: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicGainsLossesTransparencyGet200ResponseLast20Inner
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof PublicGainsLossesTransparencyGet200ResponseLast20Inner
     */
    reason: string;
    /**
     * 
     * @type {number}
     * @memberof PublicGainsLossesTransparencyGet200ResponseLast20Inner
     */
    timestamp: number;
}

/**
 * Check if a given object implements the PublicGainsLossesTransparencyGet200ResponseLast20Inner interface.
 */
export function instanceOfPublicGainsLossesTransparencyGet200ResponseLast20Inner(value: object): value is PublicGainsLossesTransparencyGet200ResponseLast20Inner {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function PublicGainsLossesTransparencyGet200ResponseLast20InnerFromJSON(json: any): PublicGainsLossesTransparencyGet200ResponseLast20Inner {
    return PublicGainsLossesTransparencyGet200ResponseLast20InnerFromJSONTyped(json, false);
}

export function PublicGainsLossesTransparencyGet200ResponseLast20InnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicGainsLossesTransparencyGet200ResponseLast20Inner {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'network': json['network'],
        'amount': json['amount'],
        'reason': json['reason'],
        'timestamp': json['timestamp'],
    };
}

export function PublicGainsLossesTransparencyGet200ResponseLast20InnerToJSON(json: any): PublicGainsLossesTransparencyGet200ResponseLast20Inner {
    return PublicGainsLossesTransparencyGet200ResponseLast20InnerToJSONTyped(json, false);
}

export function PublicGainsLossesTransparencyGet200ResponseLast20InnerToJSONTyped(value?: PublicGainsLossesTransparencyGet200ResponseLast20Inner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'network': value['network'],
        'amount': value['amount'],
        'reason': value['reason'],
        'timestamp': value['timestamp'],
    };
}

