/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicCurrenciesGet200ResponseInnerNetworksInner } from './PublicCurrenciesGet200ResponseInnerNetworksInner';
import {
    PublicCurrenciesGet200ResponseInnerNetworksInnerFromJSON,
    PublicCurrenciesGet200ResponseInnerNetworksInnerFromJSONTyped,
    PublicCurrenciesGet200ResponseInnerNetworksInnerToJSON,
    PublicCurrenciesGet200ResponseInnerNetworksInnerToJSONTyped,
} from './PublicCurrenciesGet200ResponseInnerNetworksInner';

/**
 * 
 * @export
 * @interface PublicCurrenciesGet200ResponseInner
 */
export interface PublicCurrenciesGet200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof PublicCurrenciesGet200ResponseInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PublicCurrenciesGet200ResponseInner
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof PublicCurrenciesGet200ResponseInner
     */
    precision: number;
    /**
     * 
     * @type {string}
     * @memberof PublicCurrenciesGet200ResponseInner
     */
    valueUsd: string;
    /**
     * 
     * @type {string}
     * @memberof PublicCurrenciesGet200ResponseInner
     */
    logoUrl: string;
    /**
     * 
     * @type {Array<PublicCurrenciesGet200ResponseInnerNetworksInner>}
     * @memberof PublicCurrenciesGet200ResponseInner
     */
    networks: Array<PublicCurrenciesGet200ResponseInnerNetworksInner>;
    /**
     * 
     * @type {any}
     * @memberof PublicCurrenciesGet200ResponseInner
     */
    depositEnabled?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PublicCurrenciesGet200ResponseInner
     */
    withdrawalEnabled?: any | null;
    /**
     * 
     * @type {string}
     * @memberof PublicCurrenciesGet200ResponseInner
     */
    lpTokenOf?: string;
}

/**
 * Check if a given object implements the PublicCurrenciesGet200ResponseInner interface.
 */
export function instanceOfPublicCurrenciesGet200ResponseInner(value: object): value is PublicCurrenciesGet200ResponseInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('precision' in value) || value['precision'] === undefined) return false;
    if (!('valueUsd' in value) || value['valueUsd'] === undefined) return false;
    if (!('logoUrl' in value) || value['logoUrl'] === undefined) return false;
    if (!('networks' in value) || value['networks'] === undefined) return false;
    return true;
}

export function PublicCurrenciesGet200ResponseInnerFromJSON(json: any): PublicCurrenciesGet200ResponseInner {
    return PublicCurrenciesGet200ResponseInnerFromJSONTyped(json, false);
}

export function PublicCurrenciesGet200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicCurrenciesGet200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'precision': json['precision'],
        'valueUsd': json['value_usd'],
        'logoUrl': json['logo_url'],
        'networks': ((json['networks'] as Array<any>).map(PublicCurrenciesGet200ResponseInnerNetworksInnerFromJSON)),
        'depositEnabled': json['deposit_enabled'] == null ? undefined : json['deposit_enabled'],
        'withdrawalEnabled': json['withdrawal_enabled'] == null ? undefined : json['withdrawal_enabled'],
        'lpTokenOf': json['lp_token_of'] == null ? undefined : json['lp_token_of'],
    };
}

export function PublicCurrenciesGet200ResponseInnerToJSON(json: any): PublicCurrenciesGet200ResponseInner {
    return PublicCurrenciesGet200ResponseInnerToJSONTyped(json, false);
}

export function PublicCurrenciesGet200ResponseInnerToJSONTyped(value?: PublicCurrenciesGet200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'precision': value['precision'],
        'value_usd': value['valueUsd'],
        'logo_url': value['logoUrl'],
        'networks': ((value['networks'] as Array<any>).map(PublicCurrenciesGet200ResponseInnerNetworksInnerToJSON)),
        'deposit_enabled': value['depositEnabled'],
        'withdrawal_enabled': value['withdrawalEnabled'],
        'lp_token_of': value['lpTokenOf'],
    };
}

