/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicExkRedeemPostRequest
 */
export interface PublicExkRedeemPostRequest {
    /**
     * 
     * @type {string}
     * @memberof PublicExkRedeemPostRequest
     */
    amount: string;
}

/**
 * Check if a given object implements the PublicExkRedeemPostRequest interface.
 */
export function instanceOfPublicExkRedeemPostRequest(value: object): value is PublicExkRedeemPostRequest {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function PublicExkRedeemPostRequestFromJSON(json: any): PublicExkRedeemPostRequest {
    return PublicExkRedeemPostRequestFromJSONTyped(json, false);
}

export function PublicExkRedeemPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicExkRedeemPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
    };
}

export function PublicExkRedeemPostRequestToJSON(json: any): PublicExkRedeemPostRequest {
    return PublicExkRedeemPostRequestToJSONTyped(json, false);
}

export function PublicExkRedeemPostRequestToJSONTyped(value?: PublicExkRedeemPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
    };
}

