/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicCurrenciesGetDefaultResponse
 */
export interface PublicCurrenciesGetDefaultResponse {
    /**
     * 
     * @type {boolean}
     * @memberof PublicCurrenciesGetDefaultResponse
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof PublicCurrenciesGetDefaultResponse
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof PublicCurrenciesGetDefaultResponse
     */
    error: string;
    /**
     * 
     * @type {string}
     * @memberof PublicCurrenciesGetDefaultResponse
     */
    details?: string;
    /**
     * 
     * @type {any}
     * @memberof PublicCurrenciesGetDefaultResponse
     */
    params?: any | null;
}

/**
 * Check if a given object implements the PublicCurrenciesGetDefaultResponse interface.
 */
export function instanceOfPublicCurrenciesGetDefaultResponse(value: object): value is PublicCurrenciesGetDefaultResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function PublicCurrenciesGetDefaultResponseFromJSON(json: any): PublicCurrenciesGetDefaultResponse {
    return PublicCurrenciesGetDefaultResponseFromJSONTyped(json, false);
}

export function PublicCurrenciesGetDefaultResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicCurrenciesGetDefaultResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'code': json['code'],
        'error': json['error'],
        'details': json['details'] == null ? undefined : json['details'],
        'params': json['params'] == null ? undefined : json['params'],
    };
}

export function PublicCurrenciesGetDefaultResponseToJSON(json: any): PublicCurrenciesGetDefaultResponse {
    return PublicCurrenciesGetDefaultResponseToJSONTyped(json, false);
}

export function PublicCurrenciesGetDefaultResponseToJSONTyped(value?: PublicCurrenciesGetDefaultResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'error': value['error'],
        'details': value['details'],
        'params': value['params'],
    };
}

