/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicMarketsGet200ResponseInnerLimitsPrice } from './PublicMarketsGet200ResponseInnerLimitsPrice';
import {
    PublicMarketsGet200ResponseInnerLimitsPriceFromJSON,
    PublicMarketsGet200ResponseInnerLimitsPriceFromJSONTyped,
    PublicMarketsGet200ResponseInnerLimitsPriceToJSON,
    PublicMarketsGet200ResponseInnerLimitsPriceToJSONTyped,
} from './PublicMarketsGet200ResponseInnerLimitsPrice';

/**
 * 
 * @export
 * @interface PublicMarketsGet200ResponseInnerLimits
 */
export interface PublicMarketsGet200ResponseInnerLimits {
    /**
     * 
     * @type {PublicMarketsGet200ResponseInnerLimitsPrice}
     * @memberof PublicMarketsGet200ResponseInnerLimits
     */
    price: PublicMarketsGet200ResponseInnerLimitsPrice;
    /**
     * 
     * @type {PublicMarketsGet200ResponseInnerLimitsPrice}
     * @memberof PublicMarketsGet200ResponseInnerLimits
     */
    amount: PublicMarketsGet200ResponseInnerLimitsPrice;
    /**
     * 
     * @type {PublicMarketsGet200ResponseInnerLimitsPrice}
     * @memberof PublicMarketsGet200ResponseInnerLimits
     */
    cost: PublicMarketsGet200ResponseInnerLimitsPrice;
}

/**
 * Check if a given object implements the PublicMarketsGet200ResponseInnerLimits interface.
 */
export function instanceOfPublicMarketsGet200ResponseInnerLimits(value: object): value is PublicMarketsGet200ResponseInnerLimits {
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('cost' in value) || value['cost'] === undefined) return false;
    return true;
}

export function PublicMarketsGet200ResponseInnerLimitsFromJSON(json: any): PublicMarketsGet200ResponseInnerLimits {
    return PublicMarketsGet200ResponseInnerLimitsFromJSONTyped(json, false);
}

export function PublicMarketsGet200ResponseInnerLimitsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicMarketsGet200ResponseInnerLimits {
    if (json == null) {
        return json;
    }
    return {
        
        'price': PublicMarketsGet200ResponseInnerLimitsPriceFromJSON(json['price']),
        'amount': PublicMarketsGet200ResponseInnerLimitsPriceFromJSON(json['amount']),
        'cost': PublicMarketsGet200ResponseInnerLimitsPriceFromJSON(json['cost']),
    };
}

export function PublicMarketsGet200ResponseInnerLimitsToJSON(json: any): PublicMarketsGet200ResponseInnerLimits {
    return PublicMarketsGet200ResponseInnerLimitsToJSONTyped(json, false);
}

export function PublicMarketsGet200ResponseInnerLimitsToJSONTyped(value?: PublicMarketsGet200ResponseInnerLimits | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'price': PublicMarketsGet200ResponseInnerLimitsPriceToJSON(value['price']),
        'amount': PublicMarketsGet200ResponseInnerLimitsPriceToJSON(value['amount']),
        'cost': PublicMarketsGet200ResponseInnerLimitsPriceToJSON(value['cost']),
    };
}

