/* tslint:disable */
/* eslint-disable */
/**
 * ExKoin API Documentation
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicExkConfigGet200ResponseRoutesValue
 */
export interface PublicExkConfigGet200ResponseRoutesValue {
    /**
     * 
     * @type {number}
     * @memberof PublicExkConfigGet200ResponseRoutesValue
     */
    weight: number;
    /**
     * 
     * @type {string}
     * @memberof PublicExkConfigGet200ResponseRoutesValue
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof PublicExkConfigGet200ResponseRoutesValue
     */
    freeAmount: number;
    /**
     * 
     * @type {number}
     * @memberof PublicExkConfigGet200ResponseRoutesValue
     */
    lockedAmount: number;
}

/**
 * Check if a given object implements the PublicExkConfigGet200ResponseRoutesValue interface.
 */
export function instanceOfPublicExkConfigGet200ResponseRoutesValue(value: object): value is PublicExkConfigGet200ResponseRoutesValue {
    if (!('weight' in value) || value['weight'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('freeAmount' in value) || value['freeAmount'] === undefined) return false;
    if (!('lockedAmount' in value) || value['lockedAmount'] === undefined) return false;
    return true;
}

export function PublicExkConfigGet200ResponseRoutesValueFromJSON(json: any): PublicExkConfigGet200ResponseRoutesValue {
    return PublicExkConfigGet200ResponseRoutesValueFromJSONTyped(json, false);
}

export function PublicExkConfigGet200ResponseRoutesValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicExkConfigGet200ResponseRoutesValue {
    if (json == null) {
        return json;
    }
    return {
        
        'weight': json['weight'],
        'description': json['description'],
        'freeAmount': json['free_amount'],
        'lockedAmount': json['locked_amount'],
    };
}

export function PublicExkConfigGet200ResponseRoutesValueToJSON(json: any): PublicExkConfigGet200ResponseRoutesValue {
    return PublicExkConfigGet200ResponseRoutesValueToJSONTyped(json, false);
}

export function PublicExkConfigGet200ResponseRoutesValueToJSONTyped(value?: PublicExkConfigGet200ResponseRoutesValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'weight': value['weight'],
        'description': value['description'],
        'free_amount': value['freeAmount'],
        'locked_amount': value['lockedAmount'],
    };
}

